### ISSUE TITLE
Crash with latest Xaero's Minimap (MC 1.12)

### ISSUE THREAD

**Issue by greysondn** [duely/w2w#6]
This is basically a repeat of #5 , but whereas that issue was for 1.15 this one is for 1.12.

Generating a crash log is as easy as loading both Xaero's Minimap and this into a world, placing a waystone, naming it, and then hitting okay. Such an example follows the break, with this, Waystones Xaero's Minimap, and Xaero's World Map in a world together:

-----------

```
---- Minecraft Crash Report ----

WARNING: coremods are present:
  XaeroMinimapPlugin (Xaeros_Minimap_20.16.0.2_Forge_1.12.jar)
  XaeroWorldMapPlugin (XaerosWorldMap_1.7.4_Forge_1.12.jar)
Contact their authors BEFORE contacting forge

// Don't be sad, have a hug! <3

Time: 7/19/20 8:10 PM
Description: Updating screen events

java.lang.NoSuchMethodError: xaero/minimap/XaeroMinimap.getWaypointsManager()Lxaero/common/minimap/waypoints/WaypointsManager; (loaded from jar:file:/C:/Users/Dorian%20Greyson/Downloads/MultiMC/instances/w2w-issue/.minecraft/mods/Xaeros_Minimap_20.16.0.2_Forge_1.12.jar!/xaero/minimap/XaeroMinimap.class by net.minecraft.launchwrapper.LaunchClassLoader@3828139) called from class com.noobanidus.w2w.compat.xaerostones.WaypointHandler (loaded from jar:file:/C:/Users/Dorian%20Greyson/Downloads/MultiMC/instances/w2w-issue/.minecraft/mods/w2w-1.1.1.jar!/com/noobanidus/w2w/compat/xaerostones/WaypointHandler.class by net.minecraft.launchwrapper.LaunchClassLoader@3828139).
	at com.noobanidus.w2w.compat.xaerostones.WaypointHandler.makeWaypoint(WaypointHandler.java:17)
	at com.noobanidus.w2w.compat.xaerostones.WaystonesHandler.onWaystoneActivated(WaystonesHandler.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_50_WaystonesHandler_onWaystoneActivated_WaystoneActivatedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.blay09.mods.waystones.client.gui.GuiEditWaystone.func_146284_a(GuiEditWaystone.java:78)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.blay09.mods.waystones.client.gui.GuiEditWaystone.func_73864_a(GuiEditWaystone.java:85)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)
	at net.minecraft.client.Minecraft.func_71407_l(Minecraft.java:1759)
	at net.minecraft.client.Minecraft.func_71411_J(Minecraft.java:1098)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:398)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)


A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Client thread
Stacktrace:
	at com.noobanidus.w2w.compat.xaerostones.WaypointHandler.makeWaypoint(WaypointHandler.java:17)
	at com.noobanidus.w2w.compat.xaerostones.WaystonesHandler.onWaystoneActivated(WaystonesHandler.java:17)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler_50_WaystonesHandler_onWaystoneActivated_WaystoneActivatedEvent.invoke(.dynamic)
	at net.minecraftforge.fml.common.eventhandler.ASMEventHandler.invoke(ASMEventHandler.java:90)
	at net.minecraftforge.fml.common.eventhandler.EventBus.post(EventBus.java:182)
	at net.blay09.mods.waystones.client.gui.GuiEditWaystone.func_146284_a(GuiEditWaystone.java:78)
	at net.minecraft.client.gui.GuiScreen.func_73864_a(GuiScreen.java:443)
	at net.blay09.mods.waystones.client.gui.GuiEditWaystone.func_73864_a(GuiEditWaystone.java:85)
	at net.minecraft.client.gui.GuiScreen.func_146274_d(GuiScreen.java:533)
	at net.minecraft.client.gui.GuiScreen.func_146269_k(GuiScreen.java:501)

-- Affected screen --
Details:
	Screen name: ~~ERROR~~ NullPointerException: null

-- Affected level --
Details:
	Level name: MpServer
	All players: 1 total; [EntityPlayerSP['Sarras'/0, l='MpServer', x=2976.02, y=56.00, z=-135.74]]
	Chunk stats: MultiplayerChunkCache: 552, 552
	Level seed: 0
	Level generator: ID 01 - flat, ver 0. Features enabled: false
	Level generator options: 
	Level spawn location: World: (2970,4,-144), Chunk: (at 10,0,0 in 185,-9; contains blocks 2960,0,-144 to 2975,255,-129), Region: (5,-1; contains chunks 160,-32 to 191,-1, blocks 2560,0,-512 to 3071,255,-1)
	Level time: 937 game time, 937 day time
	Level dimension: 0
	Level storage version: 0x00000 - Unknown?
	Level weather: Rain time: 0 (now: false), thunder time: 0 (now: false)
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: false
	Forced entities: 1 total; [EntityPlayerSP['Sarras'/0, l='MpServer', x=2976.02, y=56.00, z=-135.74]]
	Retry entities: 0 total; []
	Server brand: fml,forge
	Server type: Integrated singleplayer server
Stacktrace:
	at net.minecraft.client.multiplayer.WorldClient.func_72914_a(WorldClient.java:420)
	at net.minecraft.client.Minecraft.func_71396_d(Minecraft.java:2741)
	at net.minecraft.client.Minecraft.func_99999_d(Minecraft.java:419)
	at net.minecraft.client.main.Main.main(SourceFile:123)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at net.minecraft.launchwrapper.Launch.launch(Launch.java:135)
	at net.minecraft.launchwrapper.Launch.main(Launch.java:28)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.multimc.onesix.OneSixLauncher.launchWithMainClass(OneSixLauncher.java:196)
	at org.multimc.onesix.OneSixLauncher.launch(OneSixLauncher.java:231)
	at org.multimc.EntryPoint.listen(EntryPoint.java:143)
	at org.multimc.EntryPoint.main(EntryPoint.java:34)

-- System Details --
Details:
	Minecraft Version: 1.12.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 1.8.0_262, Eclipse OpenJ9
	Java VM Version: Eclipse OpenJ9 VM (JRE 1.8.0 Windows 10 amd64-64-Bit Compressed References 20200715_763 (JIT enabled, AOT enabled)
OpenJ9   - 34cf4c075
OMR      - 113e54219
JCL      - 4fe4692246 based on jdk8u262-b10), Eclipse OpenJ9
	Memory: 660332608 bytes (629 MB) / 1059454976 bytes (1010 MB) up to 5242880000 bytes (5000 MB)
	JVM Flags: 6 total; -Xoptionsfile=C:\Program Files\AdoptOpenJDK\jdk-8.0.262.10-openj9\jre\bin\compressedrefs\options.default -Xlockword:mode=default,noLockword=java/lang/String,noLockword=java/util/MapEntry,noLockword=java/util/HashMap$Entry,noLockword=org/apache/harmony/luni/util/ModifiedMap$Entry,noLockword=java/util/Hashtable$Entry,noLockword=java/lang/invoke/MethodType,noLockword=java/lang/invoke/MethodHandle,noLockword=java/lang/invoke/CollectHandle,noLockword=java/lang/invoke/ConstructorHandle,noLockword=java/lang/invoke/ConvertHandle,noLockword=java/lang/invoke/ArgumentConversionHandle,noLockword=java/lang/invoke/AsTypeHandle,noLockword=java/lang/invoke/ExplicitCastHandle,noLockword=java/lang/invoke/FilterReturnHandle,noLockword=java/lang/invoke/DirectHandle,noLockword=java/lang/invoke/ReceiverBoundHandle,noLockword=java/lang/invoke/DynamicInvokerHandle,noLockword=java/lang/invoke/FieldHandle,noLockword=java/lang/invoke/FieldGetterHandle,noLockword=java/lang/invoke/FieldSetterHandle,noLockword=java/lang/invoke/StaticFieldGetterHandle,noLockword=java/lang/invoke/StaticFieldSetterHandle,noLockword=java/lang/invoke/IndirectHandle,noLockword=java/lang/invoke/InterfaceHandle,noLockword=java/lang/invoke/VirtualHandle,noLockword=java/lang/invoke/PrimitiveHandle,noLockword=java/lang/invoke/InvokeExactHandle,noLockword=java/lang/invoke/InvokeGenericHandle,noLockword=java/lang/invoke/VarargsCollectorHandle,noLockword=java/lang/invoke/ThunkTuple -Xjcl:jclse29 -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xms1000m -Xmx5000m
	IntCache: cache: 0, tcache: 0, allocated: 0, tallocated: 0
	FML: MCP 9.42 Powered by Forge 14.23.5.2854 10 mods loaded, 10 mods active
	States: 'U' = Unloaded 'L' = Loaded 'C' = Constructed 'H' = Pre-initialized 'I' = Initialized 'J' = Post-initialized 'A' = Available 'D' = Disabled 'E' = Errored

	| State  | ID                 | Version      | Source                                  | Signature                                |
	|:------ |:------------------ |:------------ |:--------------------------------------- |:---------------------------------------- |
	| LCHIJA | minecraft          | 1.12.2       | minecraft.jar                           | None                                     |
	| LCHIJA | mcp                | 9.42         | minecraft.jar                           | None                                     |
	| LCHIJA | FML                | 8.0.99.99    | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | forge              | 14.23.5.2854 | forge-1.12.2-14.23.5.2854-universal.jar | e3c3d50c7c986df74c645c0ac54639741c90a557 |
	| LCHIJA | xaerominimap_core  | 1.12.2-1.0   | minecraft.jar                           | None                                     |
	| LCHIJA | xaeroworldmap_core | 1.12.2-1.0   | minecraft.jar                           | None                                     |
	| LCHIJA | waystones          | 4.1.0        | Waystones_1.12.2-4.1.0.jar              | None                                     |
	| LCHIJA | xaerominimap       | 20.16.0.2    | Xaeros_Minimap_20.16.0.2_Forge_1.12.jar | None                                     |
	| LCHIJA | w2w                | 1.1.1        | w2w-1.1.1.jar                           | None                                     |
	| LCHIJA | xaeroworldmap      | 1.7.4        | XaerosWorldMap_1.7.4_Forge_1.12.jar     | None                                     |

	Loaded coremods (and transformers): 
XaeroMinimapPlugin (Xaeros_Minimap_20.16.0.2_Forge_1.12.jar)
  xaero.common.core.transformer.ChunkTransformer
  xaero.common.core.transformer.NetHandlerPlayClientTransformer
  xaero.common.core.transformer.EntityPlayerTransformer
  xaero.common.core.transformer.AbstractClientPlayerTransformer
XaeroWorldMapPlugin (XaerosWorldMap_1.7.4_Forge_1.12.jar)
  xaero.map.core.transformer.ChunkTransformer
  xaero.map.core.transformer.NetHandlerPlayClientTransformer
  xaero.map.core.transformer.EntityPlayerTransformer
  xaero.map.core.transformer.AbstractClientPlayerTransformer
	GL info: ' Vendor: 'ATI Technologies Inc.' Version: '4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000' Renderer: 'AMD Radeon(TM) Vega 8 Graphics'
	Launched Version: MultiMC5
	LWJGL: 2.9.4
	OpenGL: AMD Radeon(TM) Vega 8 Graphics GL version 4.6.13587 Compatibility Profile Context 20.2.2 26.20.15019.19000, ATI Technologies Inc.
	GL Caps: Using GL 1.3 multitexturing.
Using GL 1.3 texture combiners.
Using framebuffer objects because OpenGL 3.0 is supported and separate blending is supported.
Shaders are available because OpenGL 2.1 is supported.
VBOs are available because OpenGL 1.5 is supported.

	Using VBOs: Yes
	Is Modded: Definitely; Client brand changed to 'fml,forge'
	Type: Client (map_client.txt)
	Resource Packs: 
	Current Language: English (US)
	Profiler Position: N/A (disabled)
	CPU: 8x AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx 
```

**Comment by noobanidus** [comment]
I just uploaded a new 1.12.2 version that hopefully fixes it! This time I remembered, but thank you for the reminding report otherwise if I'd forgotten I would've just forgotten.

**Comment by greysondn** [comment]
Tested with both local and server. Local was just the short set from the first remark here; server is like 140 mods. Working in both cases. This should be okay to close.

Thank you so much!

**Comment by noobanidus** [comment]
Awesome, thanks!
